In [1]:
import torch
from sklearn.model_selection import train_test_split
import pandas as pd
import torch.nn as nn
import numpy as np
from sklearn.preprocessing import StandardScaler
import csv

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
meteo_old = pd.read_csv("/./in-sample/2024_meteo_act_comuneimpianto.csv", sep=";")
meteo= pd.read_csv("./in-sample/augmented_data_finale.csv", sep=",")
prod = pd.read_excel("./in-sample/produzione_2024.xlsx")

In [4]:
meteo.head()

,Dataora,wds_comuneimpianto,wdd_comuneimpianto,rnf_comuneimpianto,rhm_comuneimpianto,wds_comunelimitrofo1,wdd_comunelimitrofo1,rnf_comunelimitrofo1,rhm_comunelimitrofo1,wds_comunelimitrofo2,...,media_wds3_tutti,std_wds3_tutti,media_u_tutti,std_u_tutti,media_v_tutti,std_v_tutti,media_rnf_tutti,std_rnf_tutti,media_rhm_tutti,std_rhm_tutti
0,2024-01-01 00:00:00,16.8,204.3,0.0,82.6,22.0,223.3,0.0,84.5,22.1,...,9169.419400,2412.420042,-15.435112,0.669001,-13.584405,3.737179,0.0,0.0,87.08,3.526613
1,2024-01-01 01:00:00,16.5,200.6,0.0,82.5,24.1,222.2,0.0,84.6,24.2,...,10867.078867,3486.115394,-16.719496,1.147870,-14.446141,4.844506,0.0,0.0,86.94,3.434094
2,2024-01-01 02:00:00,15.2,199.0,0.0,82.7,25.8,223.7,0.0,84.2,25.9,...,12355.717222,4674.618379,-17.348976,1.847225,-15.276205,5.781740,0.0,0.0,86.60,3.261135
3,2024-01-01 03:00:00,13.3,202.8,0.0,83.4,24.4,224.6,0.0,84.2,25.1,...,12258.144844,4884.092865,-16.196080,2.317481,-15.058037,5.557419,0.0,0.0,87.40,3.595136
4,2024-01-01 04:00:00,11.7,198.6,0.0,84.5,21.5,226.7,0.0,84.7,24.1,...,11537.142151,5038.222146,-14.979914,2.393150,-14.468829,6.098506,0.0,0.0,87.92,3.262208

In [5]:
#meteo["month"] = pd.to_datetime(meteo["Dataora"]).dt.month
#meteo["month"] = np.sin(meteo["month"]*2*3.14/12)
target = "Mwh"
Y = prod[target]
X = meteo.drop(columns=["Dataora"])
unito = pd.concat([X, Y], axis=1)

In [6]:
unito.dropna(inplace=True)

In [7]:
Y = unito[target]
X = unito.drop(columns=[target])
X.head()

print(X.shape)

(8733, 96)

In [8]:
train_ratio = 0.80
validation_ratio = 0.20
x_train, x_valid, y_train, y_valid = train_test_split(X, Y, test_size=1 - train_ratio, shuffle=False)
x_train2 = X.iloc[:7000,:4]
x_valid2 = X.iloc[7000:,:4]
y_train2 = Y.iloc[:7000]
y_valid2 = Y.iloc[7000:]
x_train2.shape

(7000, 4)

In [9]:
x_train = torch.from_numpy(x_train.values).float()
y_train = torch.from_numpy(y_train.values).float()
x_valid = torch.from_numpy(x_valid.values).float()
y_valid = torch.from_numpy(y_valid.values).float()

x_train2 = torch.from_numpy(x_train2.values).float()
y_train2 = torch.from_numpy(y_train2.values).float()
x_valid2 = torch.from_numpy(x_valid2.values).float()
y_valid2 = torch.from_numpy(y_valid2.values).float()

In [10]:
class mydataset:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __len__(self):
        return len(self.y)
    def __getitem__(self, idx):
        return self.x[idx,:], self.y[idx]

In [11]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.Sequential(
            nn.LayerNorm(96),
            nn.Linear(96, 64),
            nn.ReLU(),
            nn.LayerNorm(64),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.LayerNorm(32),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.layers(x)

In [4]:
class MLP2(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.Sequential(
            nn.LayerNorm(96),
            nn.Linear(96, 32),
            nn.ReLU(),
            nn.LayerNorm(32),
            nn.Linear(32, 1),
            nn.ReLU()
        )

    def forward(self, x):
        return self.layers(x)

In [37]:
net = MLP2().to(device)
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.001,  weight_decay=1e-4)

In [32]:
traindata = mydataset(x_train, y_train)
validdata = mydataset(x_valid, y_valid)

trainloader = torch.utils.data.DataLoader(traindata, batch_size=16, shuffle=True, num_workers=2)
testloader = torch.utils.data.DataLoader(validdata, batch_size=16, shuffle=True, num_workers=2)

alldata = torch.utils.data.ConcatDataset([traindata, validdata])
allloader = torch.utils.data.DataLoader(alldata, batch_size=16, shuffle=True, num_workers=2)

In [33]:
def evalstep(epoch):

    net.eval()
    outputs = []
    with torch.no_grad():
        for i in range(len(validdata)):
            inputs, targets = validdata.x[i,:], validdata.y[i]
            if inputs.dim() == 1:
                inputs = inputs.unsqueeze(0)
            inputs, targets = inputs.float().to(device), targets.float().to(device)

            outputs.append(net(inputs))

        
    loss = custom_loss(outputs, validdata.y)
    print(f'Epoch: {epoch} Custom Loss: {loss.item()}')

In [34]:
def train_step(model, optimizer, loss_function, trainloader, epochs = 20):
    for epoch in range(0, epochs):
        print(f'Starting Epoch {epoch+1}')

        current_loss = 0.0

        for i, data in enumerate(trainloader, 0):
            inputs, targets = data
            inputs, targets = inputs.float().to(device), targets.float().to(device)
     
            targets = targets.reshape((targets.shape[0], 1))

            optimizer.zero_grad()

            outputs = model(inputs)

            loss = loss_function(outputs, targets)

            loss.backward()

            optimizer.step()

            current_loss += loss.item()
        evalstep(epoch)
        print(f'Epoch {epoch+1} finished')

    print("Training has completed")

In [35]:
def custom_loss(outputs, targets):
    sum = 0
    for i in range(len(outputs)):
        sum += abs(outputs[i] - targets[i])
    return sum / abs(targets).sum()

In [ ]:
train_step(net, optimizer, loss_function, trainloader, epochs=300)

In [11]:
def evalstep(epoch):

    net.eval()
    outputs = []
    with torch.no_grad():
        for i in range(len(validdata)):
            inputs, targets = validdata.x[i,:], validdata.y[i]
            if inputs.dim() == 1:
                inputs = inputs.unsqueeze(0)
            inputs, targets = inputs.float().to(device), targets.float().to(device)

            outputs.append(net(inputs))

        
    loss = custom_loss(outputs, validdata.y)
    print(f'Epoch: {epoch} Custom Loss: {loss.item()}')

In [38]:
train_step(net, optimizer, loss_function, allloader, epochs=35)

Starting Epoch 1
Epoch: 0 Custom Loss: 0.5213763117790222
Epoch 1 finished
Starting Epoch 2
Epoch: 1 Custom Loss: 0.48138076066970825
Epoch 2 finished
Starting Epoch 3
Epoch: 2 Custom Loss: 0.4605843126773834
Epoch 3 finished
Starting Epoch 4
Epoch: 3 Custom Loss: 0.44761210680007935
Epoch 4 finished
Starting Epoch 5
Epoch: 4 Custom Loss: 0.4676322638988495
Epoch 5 finished
Starting Epoch 6
Epoch: 5 Custom Loss: 0.5413516759872437
Epoch 6 finished
Starting Epoch 7
Epoch: 6 Custom Loss: 0.44937267899513245
Epoch 7 finished
Starting Epoch 8
Epoch: 7 Custom Loss: 0.39490774273872375
Epoch 8 finished
Starting Epoch 9
Epoch: 8 Custom Loss: 0.4058789610862732
Epoch 9 finished
Starting Epoch 10
Epoch: 9 Custom Loss: 0.41580653190612793
Epoch 10 finished
Starting Epoch 11
Epoch: 10 Custom Loss: 0.43149566650390625
Epoch 11 finished
Starting Epoch 12
Epoch: 11 Custom Loss: 0.3926028311252594
Epoch 12 finished
Starting Epoch 13
Epoch: 12 Custom Loss: 0.36667588353157043
Epoch 13 finished
Starting Epoch 14
Epoch: 13 Custom Loss: 0.35434338450431824
Epoch 14 finished
Starting Epoch 15
Epoch: 14 Custom Loss: 0.4734903872013092
Epoch 15 finished
Starting Epoch 16
Epoch: 15 Custom Loss: 0.3874785602092743
Epoch 16 finished
Starting Epoch 17
Epoch: 16 Custom Loss: 0.34688255190849304
Epoch 17 finished
Starting Epoch 18
Epoch: 17 Custom Loss: 0.4116264879703522
Epoch 18 finished
Starting Epoch 19
Epoch: 18 Custom Loss: 0.3837260901927948
Epoch 19 finished
Starting Epoch 20
Epoch: 19 Custom Loss: 0.40254345536231995
Epoch 20 finished
Starting Epoch 21
Epoch: 20 Custom Loss: 0.3413354754447937
Epoch 21 finished
Starting Epoch 22
Epoch: 21 Custom Loss: 0.3965364992618561
Epoch 22 finished
Starting Epoch 23
Epoch: 22 Custom Loss: 0.37589627504348755
Epoch 23 finished
Starting Epoch 24
Epoch: 23 Custom Loss: 0.3565463125705719
Epoch 24 finished
Starting Epoch 25
Epoch: 24 Custom Loss: 0.3408174216747284
Epoch 25 finished
Starting Epoch 26
Epoch: 25 Custom Loss: 0.3483855724334717
Epoch 26 finished
Starting Epoch 27
Epoch: 26 Custom Loss: 0.3542868196964264
Epoch 27 finished
Starting Epoch 28
Epoch: 27 Custom Loss: 0.34150657057762146
Epoch 28 finished
Starting Epoch 29
Epoch: 28 Custom Loss: 0.3772604465484619
Epoch 29 finished
Starting Epoch 30
Epoch: 29 Custom Loss: 0.33751165866851807
Epoch 30 finished
Starting Epoch 31
Epoch: 30 Custom Loss: 0.3373642563819885
Epoch 31 finished
Starting Epoch 32
Epoch: 31 Custom Loss: 0.33274972438812256
Epoch 32 finished
Starting Epoch 33
Epoch: 32 Custom Loss: 0.33663511276245117
Epoch 33 finished
Starting Epoch 34
Epoch: 33 Custom Loss: 0.3751300871372223
Epoch 34 finished
Starting Epoch 35
Epoch: 34 Custom Loss: 0.3412474989891052
Epoch 35 finished
Training has completed

In [39]:
torch.save(net.state_dict(), "eznnfinal.pth")

In [16]:
class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, layer_dim, output_dim):
        super(LSTMModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.layer_dim = layer_dim
        self.norm = nn.LayerNorm(input_dim)
        self.lstm = nn.LSTM(input_dim, hidden_dim, layer_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, h0=None, c0=None):
        if h0 is None or c0 is None:
            h0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
            c0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
        x = self.norm(x)
        out, (hn, cn) = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out, hn, cn

In [38]:
model = LSTMModel(input_dim=20, hidden_dim=64, layer_dim=1, output_dim=1)
model.to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1, weight_decay=1e-5)

In [39]:
sequence_length = 5

def create_sequences(x, y, seq_len):
    xs, ys = [], []
    for i in range(len(x) - seq_len):
        xs.append(x[i:i+seq_len])
        ys.append(y[i+seq_len])
    return torch.stack(xs), torch.stack(ys)

x_seq, y_seq = create_sequences(x_train2, y_train2, sequence_length)

In [40]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=1e-4)

In [41]:
def predict_on_x_valid(model, x_valid, device='cuda'):
    model.eval()
    
    x_valid_seq = x_valid.unsqueeze(1).to(device)

    with torch.no_grad():
        tmp, _, _ = model(x_valid_seq)

    return tmp.unsqueeze(1)

In [ ]:
num_epochs = 2000
h0, c0 = None, None

for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()

    inputs = x_seq.to(device)
    targets = y_seq.unsqueeze(1).to(device)

    outputs, h0, c0 = model(inputs, h0, c0)
    loss = criterion(outputs, targets)
    loss.backward()
    optimizer.step()

    h0 = h0.detach()
    c0 = c0.detach()


    if (epoch+1) % 20 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')
        ypred = predict_on_x_valid(model, x_valid2, device)
        tmp = custom_loss(ypred, y_valid)

        print(f'Custom Loss: {tmp.item()}')

In [64]:
ypred = predict_on_x_valid(model, x_valid, device)

In [65]:
loss = custom_loss(ypred, y_valid)

print(f'Custom Loss: {loss.item()}')

Custom Loss: 1.4644279479980469

In [6]:
net = torch.load('eznnfinal.pth')

In [ ]:
meteo= pd.read_csv("./augmented_dataset.csv", sep=",")

In [8]:
target = "Mwh"
Y = prod[target]
X = meteo.drop(columns=["Dataora"])
unito = pd.concat([X, Y], axis=1)

X.head()

,wds_comuneimpianto,wdd_comuneimpianto,rnf_comuneimpianto,rhm_comuneimpianto,wds_comunelimitrofo1,wdd_comunelimitrofo1,rnf_comunelimitrofo1,rhm_comunelimitrofo1,wds_comunelimitrofo2,wdd_comunelimitrofo2,...,media_wds3_tutti,std_wds3_tutti,media_u_tutti,std_u_tutti,media_v_tutti,std_v_tutti,media_rnf_tutti,std_rnf_tutti,media_rhm_tutti,std_rhm_tutti
0,7.0,237.2,0.0,80.4,8.8,233.5,0.0,76.9,8.8,235.3,...,548.367878,159.578000,-4.782958,0.568275,-6.922163,0.766997,0.0,0.0,80.82,2.573325
1,7.0,235.8,0.0,80.0,8.9,233.1,0.0,75.7,9.1,235.4,...,597.048611,177.228827,-4.944730,0.573290,-7.076845,0.919907,0.0,0.0,80.30,2.933428
2,6.8,235.8,0.0,79.5,8.5,233.2,0.0,74.1,8.7,235.6,...,601.559789,176.713818,-4.804956,0.554989,-6.807218,0.947215,0.0,0.0,79.28,3.266803
3,6.9,236.7,0.0,78.8,8.6,231.9,0.0,73.3,8.6,234.7,...,597.938722,173.422065,-4.848669,0.607695,-6.646031,0.864030,0.0,0.0,78.66,3.357529
4,6.5,237.9,0.0,78.6,8.1,230.4,0.0,72.6,8.3,233.7,...,582.638489,182.528582,-4.769493,0.745933,-6.373543,0.929217,0.0,0.0,78.34,3.562022

In [17]:
import torch.nn as nn
prev = []

net = MLP2()
net.load_state_dict(torch.load("eznnfinal.pth"))  # load the OrderedDict into the model
net.eval()

for i in range(0,744):
    x_tensor = torch.tensor(X.iloc[i, :], dtype=torch.float32)
    prev.append(net(x_tensor))

/tmp/ipykernel_4833/622922815.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x_tensor = torch.tensor(X.iloc[i, :], dtype=torch.float32)

In [10]:
prev

[tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.0472], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.0345], grad_fn=<ReluBackward0>),
 tensor([0.4795], grad_fn=<ReluBackward0>),
 tensor([0.7717], grad_fn=<ReluBackward0>),
 tensor([0.7926], grad_fn=<ReluBackward0>),
 tensor([0.7923], grad_fn=<ReluBackward0>),
 tensor([0.8830], grad_fn=<ReluBackward0>),
 tensor([1.0439], grad_fn=<ReluBackward0>),
 tensor([1.3904], grad_fn=<ReluBackward0>),
 tensor([1.7313], grad_fn=<ReluBackward0>),
 tensor([2.0439], grad_fn=<ReluBackward0>),
 tensor([2.2531], grad_fn=<ReluBackward0>),
 tensor([2.1517], grad_fn=<ReluBackward0>),
 tensor([2.0885], grad_fn=<ReluBackward0>),
 tensor([3.4397], grad_fn=<ReluBackward0>),
 tensor([4.8053], grad_fn=<ReluBackward0>),
 tensor([6.8493], grad_fn=<ReluBackward0>),
 tensor([9.1186], grad_fn=<ReluBackward0>),
 tensor([9.7971], grad_fn=<ReluBackward0>),
 tensor([9.9593], grad_fn=<ReluBackward0>),
 tensor([10.0202], grad_fn=<ReluBackward0>),
 tensor([10.1471], grad_fn=<ReluBackward0>),
 tensor([10.1639], grad_fn=<ReluBackward0>),
 tensor([10.3602], grad_fn=<ReluBackward0>),
 tensor([10.5526], grad_fn=<ReluBackward0>),
 tensor([10.3707], grad_fn=<ReluBackward0>),
 tensor([10.2093], grad_fn=<ReluBackward0>),
 tensor([10.4467], grad_fn=<ReluBackward0>),
 tensor([10.9096], grad_fn=<ReluBackward0>),
 tensor([11.0646], grad_fn=<ReluBackward0>),
 tensor([11.1788], grad_fn=<ReluBackward0>),
 tensor([11.1257], grad_fn=<ReluBackward0>),
 tensor([11.1889], grad_fn=<ReluBackward0>),
 tensor([11.7710], grad_fn=<ReluBackward0>),
 tensor([11.8652], grad_fn=<ReluBackward0>),
 tensor([11.6794], grad_fn=<ReluBackward0>),
 tensor([11.2015], grad_fn=<ReluBackward0>),
 tensor([11.1789], grad_fn=<ReluBackward0>),
 tensor([11.3621], grad_fn=<ReluBackward0>),
 tensor([11.7745], grad_fn=<ReluBackward0>),
 tensor([12.7493], grad_fn=<ReluBackward0>),
 tensor([13.7679], grad_fn=<ReluBackward0>),
 tensor([13.6921], grad_fn=<ReluBackward0>),
 tensor([13.9241], grad_fn=<ReluBackward0>),
 tensor([13.7427], grad_fn=<ReluBackward0>),
 tensor([12.2585], grad_fn=<ReluBackward0>),
 tensor([12.1627], grad_fn=<ReluBackward0>),
 tensor([11.1605], grad_fn=<ReluBackward0>),
 tensor([8.9898], grad_fn=<ReluBackward0>),
 tensor([7.6422], grad_fn=<ReluBackward0>),
 tensor([7.7726], grad_fn=<ReluBackward0>),
 tensor([7.7794], grad_fn=<ReluBackward0>),
 tensor([6.7442], grad_fn=<ReluBackward0>),
 tensor([5.7007], grad_fn=<ReluBackward0>),
 tensor([5.5658], grad_fn=<ReluBackward0>),
 tensor([5.1679], grad_fn=<ReluBackward0>),
 tensor([4.1007], grad_fn=<ReluBackward0>),
 tensor([4.5154], grad_fn=<ReluBackward0>),
 tensor([5.1805], grad_fn=<ReluBackward0>),
 tensor([4.2300], grad_fn=<ReluBackward0>),
 tensor([4.0994], grad_fn=<ReluBackward0>),
 tensor([3.6224], grad_fn=<ReluBackward0>),
 tensor([3.0863], grad_fn=<ReluBackward0>),
 tensor([3.0889], grad_fn=<ReluBackward0>),
 tensor([3.1837], grad_fn=<ReluBackward0>),
 tensor([2.8105], grad_fn=<ReluBackward0>),
 tensor([2.8599], grad_fn=<ReluBackward0>),
 tensor([2.7694], grad_fn=<ReluBackward0>),
 tensor([1.5592], grad_fn=<ReluBackward0>),
 tensor([0.8583], grad_fn=<ReluBackward0>),
 tensor([0.5990], grad_fn=<ReluBackward0>),
 tensor([0.4859], grad_fn=<ReluBackward0>),
 tensor([0.2582], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.0332], grad_fn=<ReluBackward0>),
 tensor([0.4424], grad_fn=<ReluBackward0>),
 tensor([0.6913], grad_fn=<ReluBackward0>),
 tensor([1.0019], grad_fn=<ReluBackward0>),
 tensor([1.0743], grad_fn=<ReluBackward0>),
 tensor([1.1493], grad_fn=<ReluBackward0>),
 tensor([1.2983], grad_fn=<ReluBackward0>),
 tensor([1.6225], grad_fn=<ReluBackward0>),
 tensor([2.2049], grad_fn=<ReluBackward0>),
 tensor([3.3020], grad_fn=<ReluBackward0>),
 tensor([4.4433], grad_fn=<ReluBackward0>),
 tensor([6.1971], grad_fn=<ReluBackward0>),
 tensor([8.9231], grad_fn=<ReluBackward0>),
 tensor([10.7933], grad_fn=<ReluBackward0>),
 tensor([10.3522], grad_fn=<ReluBackward0>),
 tensor([10.5223], grad_fn=<ReluBackward0>),
 tensor([10.0284], grad_fn=<ReluBackward0>),
 tensor([8.3554], grad_fn=<ReluBackward0>),
 tensor([6.8695], grad_fn=<ReluBackward0>),
 tensor([6.0273], grad_fn=<ReluBackward0>),
 tensor([5.6052], grad_fn=<ReluBackward0>),
 tensor([5.5753], grad_fn=<ReluBackward0>),
 tensor([5.5357], grad_fn=<ReluBackward0>),
 tensor([4.9731], grad_fn=<ReluBackward0>),
 tensor([4.8288], grad_fn=<ReluBackward0>),
 tensor([4.6997], grad_fn=<ReluBackward0>),
 tensor([4.4190], grad_fn=<ReluBackward0>),
 tensor([4.2572], grad_fn=<ReluBackward0>),
 tensor([3.7459], grad_fn=<ReluBackward0>),
 tensor([3.3904], grad_fn=<ReluBackward0>),
 tensor([3.2367], grad_fn=<ReluBackward0>),
 tensor([3.1857], grad_fn=<ReluBackward0>),
 tensor([3.2366], grad_fn=<ReluBackward0>),
 tensor([3.0071], grad_fn=<ReluBackward0>),
 tensor([3.4570], grad_fn=<ReluBackward0>),
 tensor([3.8462], grad_fn=<ReluBackward0>),
 tensor([4.2444], grad_fn=<ReluBackward0>),
 tensor([4.9439], grad_fn=<ReluBackward0>),
 tensor([5.2948], grad_fn=<ReluBackward0>),
 tensor([5.1101], grad_fn=<ReluBackward0>),
 tensor([4.2885], grad_fn=<ReluBackward0>),
 tensor([3.5847], grad_fn=<ReluBackward0>),
 tensor([3.3048], grad_fn=<ReluBackward0>),
 tensor([2.9460], grad_fn=<ReluBackward0>),
 tensor([3.0981], grad_fn=<ReluBackward0>),
 tensor([3.3130], grad_fn=<ReluBackward0>),
 tensor([3.2769], grad_fn=<ReluBackward0>),
 tensor([3.1766], grad_fn=<ReluBackward0>),
 tensor([3.1526], grad_fn=<ReluBackward0>),
 tensor([3.3288], grad_fn=<ReluBackward0>),
 tensor([3.7115], grad_fn=<ReluBackward0>),
 tensor([3.8305], grad_fn=<ReluBackward0>),
 tensor([3.7413], grad_fn=<ReluBackward0>),
 tensor([4.0036], grad_fn=<ReluBackward0>),
 tensor([4.1928], grad_fn=<ReluBackward0>),
 tensor([4.1929], grad_fn=<ReluBackward0>),
 tensor([3.9879], grad_fn=<ReluBackward0>),
 tensor([5.1510], grad_fn=<ReluBackward0>),
 tensor([5.6778], grad_fn=<ReluBackward0>),
 tensor([6.7072], grad_fn=<ReluBackward0>),
 tensor([7.7384], grad_fn=<ReluBackward0>),
 tensor([7.5168], grad_fn=<ReluBackward0>),
 tensor([6.2497], grad_fn=<ReluBackward0>),
 tensor([5.3003], grad_fn=<ReluBackward0>),
 tensor([4.8899], grad_fn=<ReluBackward0>),
 tensor([3.7731], grad_fn=<ReluBackward0>),
 tensor([3.3156], grad_fn=<ReluBackward0>),
 tensor([2.9040], grad_fn=<ReluBackward0>),
 tensor([2.3336], grad_fn=<ReluBackward0>),
 tensor([2.9643], grad_fn=<ReluBackward0>),
 tensor([3.4596], grad_fn=<ReluBackward0>),
 tensor([3.9780], grad_fn=<ReluBackward0>),
 tensor([4.3951], grad_fn=<ReluBackward0>),
 tensor([4.8416], grad_fn=<ReluBackward0>),
 tensor([5.1763], grad_fn=<ReluBackward0>),
 tensor([5.4159], grad_fn=<ReluBackward0>),
 tensor([5.3824], grad_fn=<ReluBackward0>),
 tensor([5.1955], grad_fn=<ReluBackward0>),
 tensor([4.9242], grad_fn=<ReluBackward0>),
 tensor([4.5288], grad_fn=<ReluBackward0>),
 tensor([4.6544], grad_fn=<ReluBackward0>),
 tensor([5.5426], grad_fn=<ReluBackward0>),
 tensor([6.7845], grad_fn=<ReluBackward0>),
 tensor([7.8616], grad_fn=<ReluBackward0>),
 tensor([8.7219], grad_fn=<ReluBackward0>),
 tensor([9.5081], grad_fn=<ReluBackward0>),
 tensor([9.8372], grad_fn=<ReluBackward0>),
 tensor([9.9489], grad_fn=<ReluBackward0>),
 tensor([9.8007], grad_fn=<ReluBackward0>),
 tensor([9.3906], grad_fn=<ReluBackward0>),
 tensor([9.0173], grad_fn=<ReluBackward0>),
 tensor([9.0220], grad_fn=<ReluBackward0>),
 tensor([9.2087], grad_fn=<ReluBackward0>),
 tensor([9.2945], grad_fn=<ReluBackward0>),
 tensor([9.2199], grad_fn=<ReluBackward0>),
 tensor([9.0792], grad_fn=<ReluBackward0>),
 tensor([8.5976], grad_fn=<ReluBackward0>),
 tensor([7.5487], grad_fn=<ReluBackward0>),
 tensor([6.8516], grad_fn=<ReluBackward0>),
 tensor([6.6633], grad_fn=<ReluBackward0>),
 tensor([6.5702], grad_fn=<ReluBackward0>),
 tensor([6.4170], grad_fn=<ReluBackward0>),
 tensor([6.0880], grad_fn=<ReluBackward0>),
 tensor([5.7093], grad_fn=<ReluBackward0>),
 tensor([5.5604], grad_fn=<ReluBackward0>),
 tensor([5.6914], grad_fn=<ReluBackward0>),
 tensor([5.4894], grad_fn=<ReluBackward0>),
 tensor([5.3997], grad_fn=<ReluBackward0>),
 tensor([5.4544], grad_fn=<ReluBackward0>),
 tensor([5.7314], grad_fn=<ReluBackward0>),
 tensor([7.4044], grad_fn=<ReluBackward0>),
 tensor([8.3155], grad_fn=<ReluBackward0>),
 tensor([10.4194], grad_fn=<ReluBackward0>),
 tensor([11.5330], grad_fn=<ReluBackward0>),
 tensor([11.6904], grad_fn=<ReluBackward0>),
 tensor([11.3419], grad_fn=<ReluBackward0>),
 tensor([11.1750], grad_fn=<ReluBackward0>),
 tensor([11.3154], grad_fn=<ReluBackward0>),
 tensor([11.8842], grad_fn=<ReluBackward0>),
 tensor([12.1861], grad_fn=<ReluBackward0>),
 tensor([12.6451], grad_fn=<ReluBackward0>),
 tensor([12.6121], grad_fn=<ReluBackward0>),
 tensor([12.4862], grad_fn=<ReluBackward0>),
 tensor([11.8847], grad_fn=<ReluBackward0>),
 tensor([11.9143], grad_fn=<ReluBackward0>),
 tensor([11.7783], grad_fn=<ReluBackward0>),
 tensor([11.8353], grad_fn=<ReluBackward0>),
 tensor([11.9100], grad_fn=<ReluBackward0>),
 tensor([12.8775], grad_fn=<ReluBackward0>),
 tensor([13.6489], grad_fn=<ReluBackward0>),
 tensor([13.7608], grad_fn=<ReluBackward0>),
 tensor([13.9579], grad_fn=<ReluBackward0>),
 tensor([13.7283], grad_fn=<ReluBackward0>),
 tensor([13.6718], grad_fn=<ReluBackward0>),
 tensor([13.6688], grad_fn=<ReluBackward0>),
 tensor([13.5354], grad_fn=<ReluBackward0>),
 tensor([12.9226], grad_fn=<ReluBackward0>),
 tensor([11.2541], grad_fn=<ReluBackward0>),
 tensor([8.4458], grad_fn=<ReluBackward0>),
 tensor([5.2402], grad_fn=<ReluBackward0>),
 tensor([1.7796], grad_fn=<ReluBackward0>),
 tensor([0.8274], grad_fn=<ReluBackward0>),
 tensor([0.5707], grad_fn=<ReluBackward0>),
 tensor([0.7573], grad_fn=<ReluBackward0>),
 tensor([0.6288], grad_fn=<ReluBackward0>),
 tensor([0.1974], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.6325], grad_fn=<ReluBackward0>),
 tensor([1.5412], grad_fn=<ReluBackward0>),
 tensor([1.2015], grad_fn=<ReluBackward0>),
 tensor([0.3462], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.6499], grad_fn=<ReluBackward0>),
 tensor([0.5325], grad_fn=<ReluBackward0>),
 tensor([1.0864], grad_fn=<ReluBackward0>),
 tensor([3.2347], grad_fn=<ReluBackward0>),
 tensor([3.0248], grad_fn=<ReluBackward0>),
 tensor([6.7023], grad_fn=<ReluBackward0>),
 tensor([9.6039], grad_fn=<ReluBackward0>),
 tensor([10.3628], grad_fn=<ReluBackward0>),
 tensor([11.4127], grad_fn=<ReluBackward0>),
 tensor([9.9864], grad_fn=<ReluBackward0>),
 tensor([9.9400], grad_fn=<ReluBackward0>),
 tensor([11.4146], grad_fn=<ReluBackward0>),
 tensor([12.1294], grad_fn=<ReluBackward0>),
 tensor([10.8582], grad_fn=<ReluBackward0>),
 tensor([8.1954], grad_fn=<ReluBackward0>),
 tensor([7.9749], grad_fn=<ReluBackward0>),
 tensor([8.0976], grad_fn=<ReluBackward0>),
 tensor([8.1122], grad_fn=<ReluBackward0>),
 tensor([8.0757], grad_fn=<ReluBackward0>),
 tensor([8.0535], grad_fn=<ReluBackward0>),
 tensor([8.9007], grad_fn=<ReluBackward0>),
 tensor([9.1193], grad_fn=<ReluBackward0>),
 tensor([9.1348], grad_fn=<ReluBackward0>),
 tensor([9.0689], grad_fn=<ReluBackward0>),
 tensor([10.1059], grad_fn=<ReluBackward0>),
 tensor([10.7675], grad_fn=<ReluBackward0>),
 tensor([11.6841], grad_fn=<ReluBackward0>),
 tensor([12.4740], grad_fn=<ReluBackward0>),
 tensor([12.1306], grad_fn=<ReluBackward0>),
 tensor([12.1644], grad_fn=<ReluBackward0>),
 tensor([12.1528], grad_fn=<ReluBackward0>),
 tensor([11.8920], grad_fn=<ReluBackward0>),
 tensor([11.7476], grad_fn=<ReluBackward0>),
 tensor([11.6883], grad_fn=<ReluBackward0>),
 tensor([11.8176], grad_fn=<ReluBackward0>),
 tensor([11.9987], grad_fn=<ReluBackward0>),
 tensor([11.8933], grad_fn=<ReluBackward0>),
 tensor([11.6941], grad_fn=<ReluBackward0>),
 tensor([9.5407], grad_fn=<ReluBackward0>),
 tensor([8.4164], grad_fn=<ReluBackward0>),
 tensor([8.1915], grad_fn=<ReluBackward0>),
 tensor([7.9827], grad_fn=<ReluBackward0>),
 tensor([8.6141], grad_fn=<ReluBackward0>),
 tensor([8.6187], grad_fn=<ReluBackward0>),
 tensor([8.5428], grad_fn=<ReluBackward0>),
 tensor([8.5113], grad_fn=<ReluBackward0>),
 tensor([8.1033], grad_fn=<ReluBackward0>),
 tensor([8.1711], grad_fn=<ReluBackward0>),
 tensor([8.9719], grad_fn=<ReluBackward0>),
 tensor([10.0507], grad_fn=<ReluBackward0>),
 tensor([9.8486], grad_fn=<ReluBackward0>),
 tensor([9.3775], grad_fn=<ReluBackward0>),
 tensor([10.0222], grad_fn=<ReluBackward0>),
 tensor([9.1939], grad_fn=<ReluBackward0>),
 tensor([8.6914], grad_fn=<ReluBackward0>),
 tensor([8.4208], grad_fn=<ReluBackward0>),
 tensor([7.4909], grad_fn=<ReluBackward0>),
 tensor([8.0082], grad_fn=<ReluBackward0>),
 tensor([9.1713], grad_fn=<ReluBackward0>),
 tensor([9.7008], grad_fn=<ReluBackward0>),
 tensor([9.4800], grad_fn=<ReluBackward0>),
 tensor([8.3938], grad_fn=<ReluBackward0>),
 tensor([8.3541], grad_fn=<ReluBackward0>),
 tensor([9.5672], grad_fn=<ReluBackward0>),
 tensor([11.0507], grad_fn=<ReluBackward0>),
 tensor([11.7945], grad_fn=<ReluBackward0>),
 tensor([12.2614], grad_fn=<ReluBackward0>),
 tensor([13.7912], grad_fn=<ReluBackward0>),
 tensor([14.2376], grad_fn=<ReluBackward0>),
 tensor([13.6989], grad_fn=<ReluBackward0>),
 tensor([12.6361], grad_fn=<ReluBackward0>),
 tensor([11.7181], grad_fn=<ReluBackward0>),
 tensor([11.1229], grad_fn=<ReluBackward0>),
 tensor([10.0026], grad_fn=<ReluBackward0>),
 tensor([10.6298], grad_fn=<ReluBackward0>),
 tensor([11.4528], grad_fn=<ReluBackward0>),
 tensor([11.6270], grad_fn=<ReluBackward0>),
 tensor([11.3765], grad_fn=<ReluBackward0>),
 tensor([10.3034], grad_fn=<ReluBackward0>),
 tensor([10.9710], grad_fn=<ReluBackward0>),
 tensor([11.4971], grad_fn=<ReluBackward0>),
 tensor([14.1672], grad_fn=<ReluBackward0>),
 tensor([13.1145], grad_fn=<ReluBackward0>),
 tensor([11.7548], grad_fn=<ReluBackward0>),
 tensor([10.4684], grad_fn=<ReluBackward0>),
 tensor([12.2514], grad_fn=<ReluBackward0>),
 tensor([12.7731], grad_fn=<ReluBackward0>),
 tensor([11.9133], grad_fn=<ReluBackward0>),
 tensor([9.1961], grad_fn=<ReluBackward0>),
 tensor([9.0717], grad_fn=<ReluBackward0>),
 tensor([9.8762], grad_fn=<ReluBackward0>),
 tensor([6.2208], grad_fn=<ReluBackward0>),
 tensor([6.5165], grad_fn=<ReluBackward0>),
 tensor([4.8100], grad_fn=<ReluBackward0>),
 tensor([4.5493], grad_fn=<ReluBackward0>),
 tensor([5.4227], grad_fn=<ReluBackward0>),
 tensor([6.7626], grad_fn=<ReluBackward0>),
 tensor([6.0315], grad_fn=<ReluBackward0>),
 tensor([5.5478], grad_fn=<ReluBackward0>),
 tensor([4.4512], grad_fn=<ReluBackward0>),
 tensor([4.7419], grad_fn=<ReluBackward0>),
 tensor([5.9472], grad_fn=<ReluBackward0>),
 tensor([7.1057], grad_fn=<ReluBackward0>),
 tensor([6.5103], grad_fn=<ReluBackward0>),
 tensor([6.1230], grad_fn=<ReluBackward0>),
 tensor([5.6564], grad_fn=<ReluBackward0>),
 tensor([4.0183], grad_fn=<ReluBackward0>),
 tensor([2.9605], grad_fn=<ReluBackward0>),
 tensor([3.1901], grad_fn=<ReluBackward0>),
 tensor([2.8835], grad_fn=<ReluBackward0>),
 tensor([2.4331], grad_fn=<ReluBackward0>),
 tensor([2.1314], grad_fn=<ReluBackward0>),
 tensor([1.4938], grad_fn=<ReluBackward0>),
 tensor([0.8936], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.6189], grad_fn=<ReluBackward0>),
 tensor([0.7193], grad_fn=<ReluBackward0>),
 tensor([0.5740], grad_fn=<ReluBackward0>),
 tensor([0.6758], grad_fn=<ReluBackward0>),
 tensor([0.8636], grad_fn=<ReluBackward0>),
 tensor([0.9225], grad_fn=<ReluBackward0>),
 tensor([1.4621], grad_fn=<ReluBackward0>),
 tensor([1.8011], grad_fn=<ReluBackward0>),
 tensor([2.0620], grad_fn=<ReluBackward0>),
 tensor([2.0908], grad_fn=<ReluBackward0>),
 tensor([1.6530], grad_fn=<ReluBackward0>),
 tensor([1.6512], grad_fn=<ReluBackward0>),
 tensor([2.1864], grad_fn=<ReluBackward0>),
 tensor([1.9389], grad_fn=<ReluBackward0>),
 tensor([1.7272], grad_fn=<ReluBackward0>),
 tensor([2.0819], grad_fn=<ReluBackward0>),
 tensor([2.5378], grad_fn=<ReluBackward0>),
 tensor([3.1463], grad_fn=<ReluBackward0>),
 tensor([3.8423], grad_fn=<ReluBackward0>),
 tensor([4.1590], grad_fn=<ReluBackward0>),
 tensor([5.0931], grad_fn=<ReluBackward0>),
 tensor([5.1181], grad_fn=<ReluBackward0>),
 tensor([6.2083], grad_fn=<ReluBackward0>),
 tensor([6.2792], grad_fn=<ReluBackward0>),
 tensor([6.5755], grad_fn=<ReluBackward0>),
 tensor([7.0378], grad_fn=<ReluBackward0>),
 tensor([6.8563], grad_fn=<ReluBackward0>),
 tensor([7.3857], grad_fn=<ReluBackward0>),
 tensor([7.7980], grad_fn=<ReluBackward0>),
 tensor([7.7368], grad_fn=<ReluBackward0>),
 tensor([8.5487], grad_fn=<ReluBackward0>),
 tensor([8.6693], grad_fn=<ReluBackward0>),
 tensor([9.0445], grad_fn=<ReluBackward0>),
 tensor([9.3155], grad_fn=<ReluBackward0>),
 tensor([8.8376], grad_fn=<ReluBackward0>),
 tensor([8.6520], grad_fn=<ReluBackward0>),
 tensor([10.2192], grad_fn=<ReluBackward0>),
 tensor([11.4703], grad_fn=<ReluBackward0>),
 tensor([11.5005], grad_fn=<ReluBackward0>),
 tensor([11.7599], grad_fn=<ReluBackward0>),
 tensor([12.7417], grad_fn=<ReluBackward0>),
 tensor([12.8665], grad_fn=<ReluBackward0>),
 tensor([12.9404], grad_fn=<ReluBackward0>),
 tensor([12.2224], grad_fn=<ReluBackward0>),
 tensor([13.5738], grad_fn=<ReluBackward0>),
 tensor([14.6518], grad_fn=<ReluBackward0>),
 tensor([14.4131], grad_fn=<ReluBackward0>),
 tensor([13.8754], grad_fn=<ReluBackward0>),
 tensor([13.5529], grad_fn=<ReluBackward0>),
 tensor([13.4237], grad_fn=<ReluBackward0>),
 tensor([14.2285], grad_fn=<ReluBackward0>),
 tensor([13.0997], grad_fn=<ReluBackward0>),
 tensor([12.8177], grad_fn=<ReluBackward0>),
 tensor([12.5663], grad_fn=<ReluBackward0>),
 tensor([13.5072], grad_fn=<ReluBackward0>),
 tensor([13.7951], grad_fn=<ReluBackward0>),
 tensor([13.1306], grad_fn=<ReluBackward0>),
 tensor([11.9213], grad_fn=<ReluBackward0>),
 tensor([10.1774], grad_fn=<ReluBackward0>),
 tensor([8.9441], grad_fn=<ReluBackward0>),
 tensor([5.3740], grad_fn=<ReluBackward0>),
 tensor([4.5897], grad_fn=<ReluBackward0>),
 tensor([3.8404], grad_fn=<ReluBackward0>),
 tensor([2.0404], grad_fn=<ReluBackward0>),
 tensor([1.9819], grad_fn=<ReluBackward0>),
 tensor([1.2963], grad_fn=<ReluBackward0>),
 tensor([0.4284], grad_fn=<ReluBackward0>),
 tensor([0.2462], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.2945], grad_fn=<ReluBackward0>),
 tensor([0.0241], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),
 tensor([0.], grad_fn=<ReluBackward0>),

In [20]:
with open('res.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    for v in prev:
        writer.writerow([v.item()])  # Convert tensor to scalar value